<template>
  <div class="loadingio-spinner-dual-ring-t4s7uqon2w">
    <div class="ldio-nx83ullx2u8">
      <div></div>
      <div>
        <div></div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: "loader",
  components: {}
};
</script>
<style lang="scss" scoped>
@keyframes ldio-nx83ullx2u8 {
  0% {
    transform: rotate(0);
  }

  100% {
    transform: rotate(360deg);
  }
}

.ldio-nx83ullx2u8 {
  div {
    box-sizing: border-box !important;
  }

  > div {
    position: absolute;
    width: 144px;
    height: 144px;
    top: 28px;
    left: 28px;
    border-radius: 50%;
    border: 16px solid #000;
    border-color: #ffffff transparent #ffffff transparent;
    animation: ldio-nx83ullx2u8 1s linear infinite;

    &:nth-child(2) {
      border-color: transparent;

      div {
        position: absolute;
        width: 100%;
        height: 100%;
        transform: rotate(45deg);

        &:before {
          content: "";
          display: block;
          position: absolute;
          width: 16px;
          height: 16px;
          top: -16px;
          left: 48px;
          background: #ffffff;
          border-radius: 50%;
          box-shadow: 0 128px 0 0 #ffffff;
        }

        &:after {
          content: "";
          display: block;
          position: absolute;
          width: 16px;
          height: 16px;
          top: -16px;
          left: 48px;
          background: #ffffff;
          border-radius: 50%;
          box-shadow: 0 128px 0 0 #ffffff;
          left: -16px;
          top: 48px;
          box-shadow: 128px 0 0 0 #ffffff;
        }
      }
    }
  }
}

.loadingio-spinner-dual-ring-t4s7uqon2w {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}

.ldio-nx83ullx2u8 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0;

  /* see note above */

  div {
    box-sizing: content-box;
  }
}

/* generated by https://loading.io/ */
</style>
